---
title: "Supplementary material"
author: "Ty Stanford and Dot Dumuid"
subtitle: "Socioeconomic disadvantage amplifies polygenic risk of overweight: A longitudinal population cohort study spanning childhood and mid-adulthood"
format: 
  docx:
    toc: true
    toc-depth: 4
    number-sections: true
    highlight-style: atom-one
    classoption: landscape
editor: source
---




```{R}
#| include: false


knitr::read_chunk('r/2_compile_results.R')
```

\newpage



```{R, libs}
#| include: false

```

```{R, consts}
#| include: false

```


\newpage

# Child data: BMI models


\newpage

## SEIFA predictor




### Table and figure by PRS

```{R, chi_bmi_prs_sei_tab}
#| echo: false
#| tbl-cap: "Estimated BMI (95% CI) across childhood by neighbourhood disadvantage (SEIFA) quintile (1=most, 5=least disadvantage), stratified by PRS quintile (1=lowest, 5=highest risk)"
```


```{R, chi_bmi_prs_sei_fig}
#| fig-width: 15
#| fig-height: 7
#| echo: false
#| fig-cap: "Estimated BMI (95% CI) across childhood by neighbourhood disadvantage (SEIFA) quintile (1=most, 5=least disadvantage), stratified by PRS quintile (1=lowest, 5=highest risk)"
```





\newpage

## SEP predictor





### Table and figure by PRS


```{R, chi_bmi_prs_sep_tab}
#| echo: false
#| tbl-cap: "Estimated BMI (95% CI) across childhood by family disadvantage (SEP) quintile (1=most, 5=least disadvantage), stratified by PRS quintile (1=lowest, 5=highest risk)"
```


```{R, chi_bmi_prs_sep_fig}
#| fig-width: 15
#| fig-height: 7
#| echo: false
#| fig-cap: "Estimated BMI (95% CI) across childhood by family disadvantage (SEP) quintile (1=most, 5=least disadvantage), stratified by PRS quintile (1=lowest, 5=highest risk)"
```




\newpage


## Marginal SEIFA and SEP Figures

```{R, chi_bmi_plot}
#| fig-width: 12
#| fig-height: 7
#| echo: false
#| fig-cap: "Association of SEIFA neighbourhood disadvantage (Panel A) and SEP family disadvantage (Panel B) with BMI across childhood. In all cases quintile 1 represents the most disadvantage."

```



\newpage



# Child data: Probability of overweight/obese models


\newpage


## SEIFA predictor




### Table and figure by PRS

```{R, chi_ovo_prs_sei_tab}
#| echo: false
#| tbl-cap: "Estimated probability of overweight/obese (95% CI) across childhood by neighbourhood disadvantage (SEIFA) quintile (1=most, 5=least disadvantage), stratified by PRS quintile (1=lowest, 5=highest risk)"
```


```{R, chi_ovo_prs_sei_fig}
#| fig-width: 15
#| fig-height: 7
#| echo: false
#| fig-cap: "Estimated probability of overweight/obese (95% CI) across childhood by neighbourhood disadvantage (SEIFA) quintile (1=most, 5=least disadvantage), stratified by PRS quintile (1=lowest, 5=highest risk)"
```






\newpage

## SEP predictor




### Table and figure by PRS


```{R, chi_ovo_prs_sep_tab}
#| echo: false
#| tbl-cap: "Estimated probability of overweight/obese (95% CI) across childhood by family disadvantage (SEP) quintile (1=most, 5=least disadvantage), stratified by PRS quintile (1=lowest, 5=highest risk)"
```

```{R, chi_ovo_prs_sep_fig}
#| fig-width: 15
#| fig-height: 7
#| echo: false
#| fig-cap: "Estimated probability of overweight/obese (95% CI) across childhood by family disadvantage (SEP) quintile (1=most, 5=least disadvantage), stratified by PRS quintile (1=lowest, 5=highest risk)"
```





\newpage

## Marginal SEIFA and SEP Figures

```{R, chi_ovo_plot}
#| fig-width: 12
#| fig-height: 7
#| echo: false
#| fig-cap: "Association of SEIFA neighbourhood disadvantage (Panel A) and SEP family disadvantage (Panel B) with probability of overweight/obese across childhood. In all cases quintile 1 represents the most disadvantage."

```














\newpage

# Adult data: BMI models


\newpage

## SEIFA predictor




### Table and figure by PRS

```{R, adu_bmi_prs_sei_tab}
#| echo: false
#| tbl-cap: "Estimated BMI (95% CI) across adulthood by neighbourhood disadvantage (SEIFA) quintile (1=most, 5=least disadvantage), stratified by PRS quintile (1=lowest, 5=highest risk)"
```


```{R, adu_bmi_prs_sei_fig}
#| fig-width: 15
#| fig-height: 7
#| echo: false
#| fig-cap: "Estimated BMI (95% CI) across adulthood by neighbourhood disadvantage (SEIFA) quintile (1=most, 5=least disadvantage), stratified by PRS quintile (1=lowest, 5=highest risk)"
```





\newpage

## SEP predictor





### Table and figure by PRS


```{R, adu_bmi_prs_sep_tab}
#| echo: false
#| tbl-cap: "Estimated BMI (95% CI) across adulthood by family disadvantage (SEP) quintile (1=most, 5=least disadvantage), stratified by PRS quintile (1=lowest, 5=highest risk)"
```


```{R, adu_bmi_prs_sep_fig}
#| fig-width: 15
#| fig-height: 7
#| echo: false
#| fig-cap: "Estimated BMI (95% CI) across adulthood by family disadvantage (SEP) quintile (1=most, 5=least disadvantage), stratified by PRS quintile (1=lowest, 5=highest risk)"
```




\newpage


## Marginal SEIFA and SEP Figures

```{R, adu_bmi_plot}
#| fig-width: 12
#| fig-height: 7
#| echo: false
#| fig-cap: "Association of SEIFA neighbourhood disadvantage (Panel A) and SEP family disadvantage (Panel B) with BMI across adulthood. In all cases quintile 1 represents the most disadvantage."

```



\newpage



# Adult data: Probability of overweight/obese models


\newpage


## SEIFA predictor




### Table and figure by PRS

```{R, adu_ovo_prs_sei_tab}
#| echo: false
#| tbl-cap: "Estimated probability of overweight/obese (95% CI) across adulthood by neighbourhood disadvantage (SEIFA) quintile (1=most, 5=least disadvantage), stratified by PRS quintile (1=lowest, 5=highest risk)"
```


```{R, adu_ovo_prs_sei_fig}
#| fig-width: 15
#| fig-height: 7
#| echo: false
#| fig-cap: "Estimated probability of overweight/obese (95% CI) across adulthood by neighbourhood disadvantage (SEIFA) quintile (1=most, 5=least disadvantage), stratified by PRS quintile (1=lowest, 5=highest risk)"
```






\newpage

## SEP predictor




### Table and figure by PRS


```{R, adu_ovo_prs_sep_tab}
#| echo: false
#| tbl-cap: "Estimated probability of overweight/obese (95% CI) across adulthood by family disadvantage (SEP) quintile (1=most, 5=least disadvantage), stratified by PRS quintile (1=lowest, 5=highest risk)"
```

```{R, adu_ovo_prs_sep_fig}
#| fig-width: 15
#| fig-height: 7
#| echo: false
#| fig-cap: "Estimated probability of overweight/obese (95% CI) across adulthood by family disadvantage (SEP) quintile (1=most, 5=least disadvantage), stratified by PRS quintile (1=lowest, 5=highest risk)"
```





\newpage

## Marginal SEIFA and SEP Figures

```{R, adu_ovo_plot}
#| fig-width: 12
#| fig-height: 7
#| echo: false
#| fig-cap: "Association of SEIFA neighbourhood disadvantage (Panel A) and SEP family disadvantage (Panel B) with probability of overweight/obese across adulthood. In all cases quintile 1 represents the most disadvantage."

```






















\newpage


# Session info


```{R}
format(Sys.time(), '%d-%b-%Y')
sessionInfo()
```


